server.port: 9090
api:
  host: "http://api.itau/apiitau" # "http://api-des.itau/"
  acceptedHeaders:
    - "execute"
    - "Content-Type"
  defaultHeaders:
    -
      headerName: "Server"
      headerValues:
        - "Microsoft-IIS/8.5"
    -
      headerName: "X-Powered-By"
      headerValues:
        - "Express,ASP.NET"
    -
      headerName: "Access-Control-Allow-Headers"
      headerValues:
        - "Content-Type"
    -
      headerName: "Access-Control-Allow-Methods"
      headerValues:
        - "GET,PUT,POST,DELETE,PATCH"
    -
      headerName: "Access-Control-Allow-Origin"
      headerValues:
        - "*"
    -
      headerName: "Connection"
      headerValues:
        - "Keep-Alive"
    -
      headerName: "Content-Type"
      headerValues:
        - "application/json;charset=utf-8"
  uriConfigurations:
    -
      host: "http://api.itau/apiitau"
      pattern: "seguranca/token"
      backup: true
    -
      host: "http://api.itau/apiitau"
      pattern: "v2/pagamento"
      backup: true
    -
      host: "http://api.itau/apiitau"
      pattern: "^(seguranca|limites_seguranca)\\/"
      backup: false
file:
  base: "/home/luis/dev/itau/ws/mobile-teste-integrado/server/fake-api-data"
  extension: ".json"
  backup.path: "/home/luis/dev/itau/ws/mobile-teste-integrado/server/fake-api-data-backup"
captureState: true
debug: true
